declare module 'postgraphile-plugin-nested-mutations'
declare module 'react-toastify'

declare global {
  interface Window {
    gtag: (event: string, action: string, options: any) => void
  }
}

interface PageProps {
  title: string
  description: string
  imageUrl?: string
  showFooter?: boolean
}

export interface Company {
  company_name: string
  industry: null
  isic: null
  lei: null
  company_url: null
  source_reports_page: null
  autogenerated_contact: null
  sustainability_contact_name: null
  sustainability_contact_email: null
  sustainability_contact_linkedin: null
  sbt_status: null
  sbt_near_term_year: null
  sbt_near_term_target: null
  net_zero_year: null
  emissions: Emission[]
  targets: Target[]
  commitment: Commitment
}

export interface CompanyResponse {
  data: Company
  error: null
}

export interface Commitment {
  lei: string
  type: string
  scope: string
  action: string
  status: string
  target: string
  'sub-type': string
  base_year: string
  year_type: string
  target_year: string
  company_name: string
  target_value: string
  date_published: Date
  target_wording: string
  commitment_type: string
  commitment_deadline: string
  full_target_language: string
  target_classification: string
  company_temperature_alignment: string
  reason_for_commitment_extension_or_removal: string
}

export interface Emission {
  year: number
  'cat._1': string
  'cat._2': string
  'cat._3': string
  'cat._4': string
  'cat._5': string
  'cat._6': string
  'cat._7': string
  'cat._8': string
  'cat._9': string
  source: string
  status: string
  'cat._10': string
  'cat._11': string
  'cat._12': string
  'cat._13': string
  'cat._14': string
  'cat._15': string
  comment: string
  revenue: string
  scope_1: string
  scope_2: string
  currency: string
  industry: string
  'all_cats?': string
  fiscal_year: string
  revenue_sek: string
  company_name: string
  ghg_standard: string
  'isic_rev._4.': string
  page_revenue: string
  scope_2_type: string
  emission_page: string
  total_scope_3: string
  source_revenue: string
  hq_country_move: string
  scope_2_unknown: string
  publication_date: string
  upstream_scope_3: string
  emission_intensity: string
  'scope_2_market-based': string
  'scope_2_location-based': string
  'source_emission_/_report': string
  total_upstream_emissions: string
  share_upstream_of_scope_3: string
  source_emisions_page_move: string
  'total_emission_market-based': string
  'total_emission_location-based': string
  'cradle-to-gate_emissions_/_sek': string
  'total_reported_emission_scope_1+2': string
  'total_reported_emission_scope_1+2+3': string
  scope_1_share_of_total_upstream_emissions: string
}

export interface Target {
  lei: string
  type: string
  scope: string
  action: string
  status: string
  target: string
  'sub-type': string
  base_year: number
  year_type: string
  target_year: number
  company_name: string
  target_value: string
  date_published: Date
  target_wording: string
  commitment_type: string
  commitment_deadline: string
  full_target_language: string
  target_classification: string
  company_temperature_alignment: string
  reason_for_commitment_extension_or_removal: string
}
